name: DeathWalls
version: ${project.version}
main: me.boomboompower.v${special.version}.deathwalls.DeathWalls
authors: [boomboompower]
commands:
   spectate:
     description: Admin command
     aliases: [spec, leave]